### ISSUE TITLE
An AnswerGenerator should be a static class with a String[] possibleAnswers and a public method to get a new random answer from the possible answers

### ISSUE THREAD

**Issue by ethansauerberg** [CSE237SP2022/project-quotdle#13]

**Comment by akshatksharma** [comment]
I can't get the tests to run on my end, but the code should be ready to go if someone else can verify it

**Comment by akshatksharma** [comment]
Was able to resolve testing issue by moving JUnit Library to classpath instead of modulepath in the project settings
